import { Component, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { Api, Auth, Challenge, errorMessage, User } from './core';
@Component({standalone:true,imports:[ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatInputModule],template:`<div class="page-heading"><div><span class="eyebrow">MAKE YOURSELF AT HOME</span><h1>Settings</h1><p class="muted">Manage your profile and account security.</p></div></div>@if(error()){<p class="error" role="alert">{{error()}}</p>}@if(message()){<p class="message" role="status">{{message()}}</p>}<div class="settings-grid"><section class="form-panel"><h2>Your profile</h2><form [formGroup]="profile" (ngSubmit)="save()"><div class="form-row"><mat-form-field><mat-label>First name</mat-label><input matInput formControlName="firstName"></mat-form-field><mat-form-field><mat-label>Last name</mat-label><input matInput formControlName="lastName"></mat-form-field></div><mat-form-field><mat-label>Phone (optional)</mat-label><input matInput formControlName="phone" type="tel"></mat-form-field><label class="upload-label" for="avatar">Profile picture · JPEG, PNG, WebP · up to 5 MiB</label><input id="avatar" type="file" accept="image/jpeg,image/png,image/webp" (change)="select($event)">@if(auth.user()?.avatarId){<img class="profile-avatar" [src]="'/api/v1/files/'+auth.user()?.avatarId" alt="Your profile picture">}<p class="muted">Email and phone are shared only with your assigned task participant.</p><button mat-flat-button [disabled]="busy()||profile.invalid">Save profile</button></form></section>
<div><section class="form-panel"><h2>Change password</h2><form [formGroup]="password" (ngSubmit)="changePassword()"><mat-form-field><mat-label>Current password</mat-label><input matInput type="password" formControlName="currentPassword" autocomplete="current-password"></mat-form-field><mat-form-field><mat-label>New password</mat-label><input matInput type="password" formControlName="password" autocomplete="new-password"><mat-error>Use at least 12 characters.</mat-error></mat-form-field><p class="muted">Changing your password signs out all sessions.</p><button mat-flat-button [disabled]="busy()||password.invalid">Change password</button></form></section>
<section class="form-panel"><h2>Change email</h2><p class="muted">Current address: {{auth.user()?.email}}</p>@if(challenge()){<form [formGroup]="otp" (ngSubmit)="verify()"><mat-form-field><mat-label>Code sent to new address</mat-label><input matInput formControlName="code" inputmode="numeric" autocomplete="one-time-code"></mat-form-field><button mat-flat-button [disabled]="busy()||otp.invalid">Verify new email</button></form><button mat-button [disabled]="busy()" (click)="resend()">Resend code (60-second cooldown)</button><p class="muted">Your old address stays active until verification.</p>}@else{<form [formGroup]="email" (ngSubmit)="changeEmail()"><mat-form-field><mat-label>New email address</mat-label><input matInput type="email" formControlName="email"></mat-form-field><mat-form-field><mat-label>Confirm current password</mat-label><input matInput type="password" formControlName="currentPassword"></mat-form-field><button mat-flat-button [disabled]="busy()||email.invalid">Send verification code</button></form>}</section></div></div>`})
export class SettingsPage {
  api=inject(Api);auth=inject(Auth);fb=inject(FormBuilder);busy=signal(false);error=signal('');message=signal('');challenge=signal<Challenge|null>(null);file?:File;
  profile=this.fb.nonNullable.group({firstName:[this.auth.user()!.firstName,[Validators.required,Validators.maxLength(60)]],lastName:[this.auth.user()!.lastName,[Validators.required,Validators.maxLength(60)]],phone:[this.auth.user()!.phone||'',[Validators.maxLength(30)]]});
  password=this.fb.nonNullable.group({currentPassword:['',Validators.required],password:['',[Validators.required,Validators.minLength(12),Validators.maxLength(128)]]});
  email=this.fb.nonNullable.group({email:['',[Validators.required,Validators.email]],currentPassword:['',Validators.required]});otp=this.fb.nonNullable.group({code:['',[Validators.required,Validators.pattern(/^\d{6}$/)]]});
  select(e:Event){this.file=(e.target as HTMLInputElement).files?.[0];}
  async run(fn:()=>Promise<void>){this.busy.set(true);this.error.set('');this.message.set('');try{await fn();}catch(e){this.error.set(errorMessage(e));}finally{this.busy.set(false);}}
  save(){return this.run(async()=>{const avatarId=this.file?(await this.api.upload(this.file,'AVATAR')).id:this.auth.user()!.avatarId;this.auth.user.set(await this.api.post<User>('auth/profile',{...this.profile.getRawValue(),avatarId}));this.message.set('Profile saved.');});}
  changePassword(){return this.run(async()=>{await this.api.post('auth/password',this.password.getRawValue());this.auth.notice.set('Password changed. Sign in again.');this.auth.expired();});}
  changeEmail(){return this.run(async()=>{this.challenge.set(await this.api.post<Challenge>('auth/email',this.email.getRawValue()));});}
  resend(){return this.run(async()=>{this.challenge.set(await this.api.post<Challenge>('auth/resend',{challengeId:this.challenge()!.challengeId}));});}
  verify(){return this.run(async()=>{const result=await this.api.post<{user:User}>('auth/verify',{challengeId:this.challenge()!.challengeId,code:this.otp.getRawValue().code});this.auth.user.set(result.user);this.challenge.set(null);this.auth.connect();this.message.set('Email verified. Other sessions have been signed out.');});}
}
