import { Component, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { Auth } from './core';
@Component({standalone:true,imports:[RouterLink,RouterLinkActive,RouterOutlet,MatButtonModule,DatePipe],template:`
<div class="app-layout" [class.menu-open]="menu()"><aside class="sidebar"><a routerLink="/feed" class="brand">h<span>HireHelper</span></a><span class="nav-label">YOUR WORKSPACE</span><nav aria-label="Main navigation">@for(link of links;track link.path){<a [routerLink]="link.path" routerLinkActive="active" (click)="menu.set(false)"><span aria-hidden="true">{{link.symbol}}</span>{{link.label}}</a>}</nav><div class="sidebar-note"><span>✦</span><h3>Small tasks.<br>Stronger communities.</h3><p>Someone nearby could use a hand like yours.</p><a routerLink="/add-task">Post your first task →</a></div><div class="sidebar-user"><div class="avatar">{{auth.user()?.firstName?.charAt(0)}}</div><div><strong>{{auth.user()?.firstName}} {{auth.user()?.lastName}}</strong><small>Community member</small></div></div></aside>
@if(menu()){<button class="menu-backdrop" aria-label="Close navigation" (click)="menu.set(false)"></button>}
<div class="workspace"><header class="topbar"><button mat-button class="menu-button" (click)="menu.set(!menu())" [attr.aria-expanded]="menu()" aria-label="Toggle navigation">☰</button><span class="topbar-caption">Make room for a little help.</span><div class="topbar-actions"><button mat-button (click)="notices.set(!notices())" [attr.aria-expanded]="notices()" aria-label="Notifications">Notifications <span class="count-badge">{{auth.unread()}}</span></button><button mat-button (click)="auth.logout()">Sign out</button></div></header>
@if(notices()){<section class="notification-panel" aria-label="Notifications"><div class="section-heading"><h3>Notifications</h3><button mat-button (click)="markAll()">Mark all read</button></div>@for(n of auth.notifications();track n.id){<a [routerLink]="n.taskId?'/tasks/'+n.taskId:'/feed'" [class.unread]="!n.readAt" (click)="read(n.id)">{{n.body}}<small>{{n.createdAt|date:'short'}}</small></a>}@empty{<p class="muted">You’re all caught up.</p>}</section>}
<main class="content" id="main-content"><router-outlet /></main><footer>HireHelper · Independently rebuilt portfolio project</footer></div></div>`})
export class Shell {auth=inject(Auth);menu=signal(false);notices=signal(false);links=[{path:'/feed',label:'Feed',symbol:'▦'},{path:'/my-tasks',label:'My Tasks',symbol:'□'},{path:'/requests',label:'Requests',symbol:'↙'},{path:'/my-requests',label:'My Requests',symbol:'↗'},{path:'/add-task',label:'Add Task',symbol:'+'},{path:'/settings',label:'Settings',symbol:'⚙'}];async markAll(){await this.auth.api.post('notifications/read-all');await this.auth.reconcile();}async read(id:string){await this.auth.api.post(`notifications/${id}/read`);await this.auth.reconcile();this.notices.set(false);}}
